version: "3.8"

services:
    db:
        image: postgres:16.6
        container_name: epayco-wallet-db
        restart: always
        environment:
            POSTGRES_DB: epayco_wallet
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U user -d epayco_wallet -h localhost",
                ]
            interval: 10s
            timeout: 5s
            retries: 3

    app:
        build: .
        container_name: epayco-wallet-app
        ports:
            - "3000:3000"
        depends_on:
            db:
                condition: service_healthy
        environment:
            PORT: 3000
            DB_HOST: db
            DB_USER: user
            DB_PASSWORD: password
            DB_NAME: epayco_wallet
        volumes:
            - .:/app
        command: "npm run dev"

    adminer:
        image: adminer
        container_name: epayco-adminer
        depends_on:
            - db
        restart: always
        ports:
            - "8080:8080"

volumes:
    app:
