<?xml version="1.0" encoding="UTF-8"?>
<definitions name="MyService"
             targetNamespace="http://www.example.org/myService/"
             xmlns:tns="http://www.example.org/myService/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.example.org/myService/">
      <!-- Operation: Register Customer -->
      <xsd:element name="registerCustomer">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="document" type="xsd:string"/>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="email" type="xsd:string"/>
            <xsd:element name="phone" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="registerCustomerResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="success" type="xsd:boolean"/>
            <xsd:element name="cod_error" type="xsd:string"/>
            <xsd:element name="message_error" type="xsd:string"/>
            <xsd:element name="data" type="xsd:string" minOccurs="0"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      
      <!-- Operation: Recharge Wallet -->
      <xsd:element name="rechargeWallet">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="document" type="xsd:string"/>
            <xsd:element name="phone" type="xsd:string"/>
            <xsd:element name="value" type="xsd:decimal"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="rechargeWalletResponse">
      <xsd:complexType>
        <xsd:sequence>
          <xsd:element name="success" type="xsd:boolean"/>
          <xsd:element name="cod_error" type="xsd:string"/>
          <xsd:element name="message_error" type="xsd:string"/>
          <xsd:element name="data" type="xsd:string" minOccurs="0"/>
        </xsd:sequence>
      </xsd:complexType>
    </xsd:element>
    </xsd:schema>
  </wsdl:types>

    <!-- Operation: Initiate Payment -->
  <xsd:element name="initiatePayment">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="document" type="xsd:string"/>
        <xsd:element name="phone" type="xsd:string"/>
        <xsd:element name="value" type="xsd:decimal"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="initiatePaymentResponse">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="success" type="xsd:boolean"/>
        <xsd:element name="cod_error" type="xsd:string"/>
        <xsd:element name="message" type="xsd:string"/>
        <xsd:element name="data" type="xsd:string" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <!-- Operation: Confirm Payment -->
  <xsd:element name="confirmPayment">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="sessionId" type="xsd:string"/>
        <xsd:element name="token" type="xsd:string"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="confirmPaymentResponse">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="success" type="xsd:boolean"/>
        <xsd:element name="cod_error" type="xsd:string"/>
        <xsd:element name="message" type="xsd:string"/>
        <xsd:element name="data" type="xsd:string" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <!-- Operation: Consult Balance -->
  <xsd:element name="consultBalance">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="document" type="xsd:string"/>
        <xsd:element name="phone" type="xsd:string"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="consultBalanceResponse">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="success" type="xsd:boolean"/>
        <xsd:element name="cod_error" type="xsd:string"/>
        <xsd:element name="message" type="xsd:string"/>
        <xsd:element name="data" type="xsd:string" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <!-- Messages -->
  <wsdl:message name="registerCustomerRequest">
    <wsdl:part name="parameters" element="tns:registerCustomer"/>
  </wsdl:message>

  <wsdl:message name="registerCustomerResponse">
    <wsdl:part name="parameters" element="tns:registerCustomerResponse"/>
  </wsdl:message>
  
  <wsdl:message name="rechargeWalletRequest">
    <wsdl:part name="parameters" element="tns:rechargeWallet"/>
  </wsdl:message>

  <wsdl:message name="rechargeWalletResponse">
    <wsdl:part name="parameters" element="tns:rechargeWalletResponse"/>
  </wsdl:message>

  <wsdl:message name="initiatePaymentRequest">
    <wsdl:part name="parameters" element="tns:initiatePayment"/>
  </wsdl:message>

  <wsdl:message name="initiatePaymentResponse">
    <wsdl:part name="parameters" element="tns:initiatePaymentResponse"/>
  </wsdl:message>

  <wsdl:message name="confirmPaymentRequest">
    <wsdl:part name="parameters" element="tns:confirmPayment"/>
  </wsdl:message>

  <wsdl:message name="confirmPaymentResponse">
    <wsdl:part name="parameters" element="tns:confirmPaymentResponse"/>
  </wsdl:message>

  <wsdl:message name="consultBalanceRequest">
    <wsdl:part name="parameters" element="tns:consultBalance"/>
  </wsdl:message>

  <wsdl:message name="consultBalanceResponse">
    <wsdl:part name="parameters" element="tns:consultBalanceResponse"/>
  </wsdl:message>
  
  <!-- Port Type -->
  <wsdl:portType name="MyPortType">
    <wsdl:operation name="registerCustomer">
      <wsdl:input message="tns:registerCustomerRequest"/>
      <wsdl:output message="tns:registerCustomerResponse"/>
    </wsdl:operation>
    <wsdl:operation name="rechargeWallet">
      <wsdl:input message="tns:rechargeWalletRequest"/>
      <wsdl:output message="tns:rechargeWalletResponse"/>
    </wsdl:operation>
    <wsdl:operation name="initiatePayment">
      <wsdl:input message="tns:initiatePaymentRequest"/>
      <wsdl:output message="tns:initiatePaymentResponse"/>
    </wsdl:operation>
    <wsdl:operation name="confirmPayment">
      <wsdl:input message="tns:confirmPaymentRequest"/>
      <wsdl:output message="tns:confirmPaymentResponse"/>
    </wsdl:operation>
    <wsdl:operation name="consultBalance">
      <wsdl:input message="tns:consultBalanceRequest"/>
      <wsdl:output message="tns:consultBalanceResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <!-- Binding -->
  <wsdl:binding name="MyBinding" type="tns:MyPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="registerCustomer">
      <soap:operation soapAction="registerCustomer"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="rechargeWallet">
      <soap:operation soapAction="rechargeWallet"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>

    <wsdl:operation name="initiatePayment">
      <soap:operation soapAction="initiatePayment"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>

    <wsdl:operation name="confirmPayment">
      <soap:operation soapAction="confirmPayment"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>

    <wsdl:operation name="consultBalance">
      <soap:operation soapAction="consultBalance"/>
    <wsdl:input>
      <soap:body use="literal"/>
    </wsdl:input>
    <wsdl:output>
      <soap:body use="literal"/>
    </wsdl:output>
    
  </wsdl:operation>

  </wsdl:binding>
  
  <!-- Service -->
  <wsdl:service name="MyService">
    <wsdl:port name="MyPort" binding="tns:MyBinding">
      <soap:address location="http://localhost:3000/soap"/>
    </wsdl:port>
  </wsdl:service>
</definitions>